pipeline {
  agent any
  stages {
    stage('Git initialize') {
      steps {
        echo 'Pull clone repository...'
        git 'clone https://github.com/63070132-song-ngan-kub-jan/week10-jenkins-dockercompose'
      }
    }
    stage('Docker build images') {
      steps {
        dir('week10-jenkins-dockercompose') {
          echo 'Start building Docker images...'
          sh 'docker-compose down --rmi all'
          sh 'docker-compose build'
        }
      }
    }
  }
}